/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canteen.sales.operations;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author WINCHESTER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        ImageIcon icon = new ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\RecaptchaLogo.svg (1) (1).png");
        checkrobot.setIcon(icon);
        
        logintxtusername.setToolTipText("Only alphanumeric characters allowed..");
        logintxtpassword.setToolTipText("At least one uppercase letter, one lowecase letter, one digit and no spaces.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logintxtusername = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logintxtpassword = new javax.swing.JPasswordField();
        checkrobot = new javax.swing.JCheckBox();
        forgotButton = new javax.swing.JButton();
        registerbutton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN PAGE");
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 88, 62, -1));

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 151, 62, -1));

        logintxtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logintxtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(logintxtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 85, 156, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 153), 5), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 51, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logintxtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logintxtpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(logintxtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 138, 158, -1));

        checkrobot.setText("I'm not a robot");
        checkrobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkrobotActionPerformed(evt);
            }
        });
        jPanel2.add(checkrobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 352, 181, 46));

        forgotButton.setBackground(new java.awt.Color(204, 153, 255));
        forgotButton.setText("I forgot my password");
        forgotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotButtonActionPerformed(evt);
            }
        });
        jPanel2.add(forgotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        registerbutton.setBackground(new java.awt.Color(204, 153, 255));
        registerbutton.setText("New register");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        cancelButton.setBackground(new java.awt.Color(255, 255, 102));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        loginButton.setBackground(new java.awt.Color(255, 255, 102));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 10, 420, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        setVisible(false);
        MainMenuUser mainPage = new MainMenuUser();
        mainPage.setVisible(true);
        

    }//GEN-LAST:event_cancelButtonActionPerformed
    

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:

        if (checkrobot.isSelected()) {
            String username = logintxtusername.getText();
            String password = new String(logintxtpassword.getPassword());
            
            Person p = DatabaseManager.login(username, password);
            if (p != null) {
                
                DatabaseManager.loggedin = p;
                JOptionPane.showMessageDialog(rootPane, "Login successful!!");
                
                this.dispose();
                
                setVisible(false);
                ProductManagment product = new ProductManagment();
                product.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid username or password", "Login failed", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            
            String errorMessage = "Please verify that you are not a robot!!!";
            JOptionPane.showMessageDialog(rootPane, errorMessage, "verifyrobot", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void forgotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ResetPassword password = new ResetPassword();
        password.setVisible(true);
    }//GEN-LAST:event_forgotButtonActionPerformed

    private void logintxtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logintxtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logintxtusernameActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        
        setVisible(false);
        Registration backLogin = new Registration();
        backLogin.setVisible(true);
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void logintxtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logintxtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logintxtpasswordActionPerformed

    private void checkrobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkrobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkrobotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox checkrobot;
    private javax.swing.JButton forgotButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField logintxtpassword;
    private javax.swing.JTextField logintxtusername;
    private javax.swing.JButton registerbutton;
    // End of variables declaration//GEN-END:variables
}
