/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canteen.sales.operations;

import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author WINCHESTER
 */
public class ProductManagment extends javax.swing.JFrame {

    /**
     * Creates new form ProductManagment
     */
    // private String item_name;
    static ArrayList<String> seleceteditemNames = new ArrayList<>();

    public ProductManagment() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        Login log = new Login();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void addtable(int id, String Name, int Qty, Double Price) {

        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

        DecimalFormat df = new DecimalFormat("00.00");

        double totPrice = Price * Double.valueOf(Qty);
        String TotalPrice = df.format(totPrice);

        // prıduct already add chk
        for (int row = 0; row < jTable1.getRowCount(); row++) {

            if (Name == jTable1.getValueAt(row, 1)) {
                dt.removeRow(jTable1.convertRowIndexToModel(row));
            }
        }

        Vector v = new Vector();

        v.add(id);
        v.add(Name);
        v.add(Qty);
        v.add(TotalPrice);

        dt.addRow(v);
    }

    public void cal() {

        int numOfRow = jTable1.getRowCount();
        double tot = 0.0;

        for (int i = 0; i < numOfRow; i++) {

            double value = Double.valueOf(jTable1.getValueAt(i, 3).toString());
            tot += value;

        }

        DecimalFormat df = new DecimalFormat("00.00");
        totalLabel.setText(df.format(tot));

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chickenbutton = new javax.swing.JButton();
        chickennnoodlebutton = new javax.swing.JButton();
        vegatarianpizzabutton = new javax.swing.JButton();
        cappuccinobutton = new javax.swing.JButton();
        coldcofeebutton = new javax.swing.JButton();
        orongejuicebutton = new javax.swing.JButton();
        rainbowcakebutton = new javax.swing.JButton();
        chocalatecakebutton = new javax.swing.JButton();
        fruitcakebutton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        countLabel1 = new javax.swing.JLabel();
        countLabel2 = new javax.swing.JLabel();
        countLabel3 = new javax.swing.JLabel();
        countLabel4 = new javax.swing.JLabel();
        countLabel5 = new javax.swing.JLabel();
        countLabel6 = new javax.swing.JLabel();
        countLabel7 = new javax.swing.JLabel();
        countLabel8 = new javax.swing.JLabel();
        countLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        btexrarea = new javax.swing.JTextArea();
        deleteButton = new javax.swing.JButton();
        evalatuionbuttom = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        pay = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        deletemyaccountbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chickenbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\chickenburgerbu.jpg")); // NOI18N
        chickenbutton.setText("jButton1");
        chickenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(chickenbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, 133, 128));

        chickennnoodlebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\chickennoodlesbu.jpg")); // NOI18N
        chickennnoodlebutton.setText("jButton2");
        chickennnoodlebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickennnoodlebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(chickennnoodlebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 19, 133, 128));

        vegatarianpizzabutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\vegetarianpizzabu.jpg")); // NOI18N
        vegatarianpizzabutton.setText("jButton3");
        vegatarianpizzabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegatarianpizzabuttonActionPerformed(evt);
            }
        });
        jPanel1.add(vegatarianpizzabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 19, 133, 128));

        cappuccinobutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\cappuccinocoffeebu.jpg")); // NOI18N
        cappuccinobutton.setText("jButton4");
        cappuccinobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinobuttonActionPerformed(evt);
            }
        });
        jPanel1.add(cappuccinobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 223, 133, 126));

        coldcofeebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\coldcoffee.jpg")); // NOI18N
        coldcofeebutton.setText("jButton5");
        coldcofeebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldcofeebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(coldcofeebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 222, 133, 128));

        orongejuicebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\orange_juice.jpg")); // NOI18N
        orongejuicebutton.setText("jButton6");
        orongejuicebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orongejuicebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(orongejuicebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 222, 133, 128));

        rainbowcakebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\rainbow.jpg")); // NOI18N
        rainbowcakebutton.setText("jButton7");
        rainbowcakebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rainbowcakebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(rainbowcakebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 424, 133, 126));

        chocalatecakebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\chocolatecake.jpg")); // NOI18N
        chocalatecakebutton.setText("jButton8");
        chocalatecakebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocalatecakebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(chocalatecakebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 424, 133, 126));

        fruitcakebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINCHESTER\\Downloads\\fruitscake (2).jpg")); // NOI18N
        fruitcakebutton.setText("jButton9");
        fruitcakebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitcakebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(fruitcakebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 424, 132, 126));

        jTextField1.setText("Chicken Burger");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 154, -1, -1));

        jTextField2.setText("Chicken Noodle");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 154, 101, -1));

        jTextField3.setText("Vegatarian Pizza");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 154, -1, -1));

        jTextField4.setText("Cappuccino");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 356, -1, -1));

        jTextField5.setText("Cold Coffe");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 356, 81, -1));

        jTextField6.setText("Orange Juice");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 356, -1, -1));

        jTextField7.setText("Rainbow Cake");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 555, -1, -1));

        jTextField8.setText("Chocolate Cake");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 555, -1, -1));

        jTextField9.setText("Fruit Cake");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 555, 71, -1));

        countLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel1.setForeground(new java.awt.Color(255, 255, 255));
        countLabel1.setText("0");
        jPanel1.add(countLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 188, -1, -1));

        countLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel2.setForeground(new java.awt.Color(255, 255, 255));
        countLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel2.setText("0");
        jPanel1.add(countLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 188, -1, -1));

        countLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel3.setForeground(new java.awt.Color(255, 255, 255));
        countLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel3.setText("0");
        jPanel1.add(countLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 188, -1, -1));

        countLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel4.setForeground(new java.awt.Color(255, 255, 255));
        countLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel4.setText("0");
        jPanel1.add(countLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 391, -1, -1));

        countLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel5.setForeground(new java.awt.Color(255, 255, 255));
        countLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel5.setText("0");
        jPanel1.add(countLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 391, -1, -1));

        countLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel6.setForeground(new java.awt.Color(255, 255, 255));
        countLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel6.setText("0");
        jPanel1.add(countLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 391, -1, -1));

        countLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel7.setForeground(new java.awt.Color(255, 255, 255));
        countLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel7.setText("0");
        jPanel1.add(countLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 589, -1, -1));

        countLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel8.setForeground(new java.awt.Color(255, 255, 255));
        countLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel8.setText("0");
        jPanel1.add(countLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 589, -1, -1));

        countLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLabel9.setForeground(new java.awt.Color(255, 255, 255));
        countLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countLabel9.setText("0");
        jPanel1.add(countLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 589, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        jTable1.setBackground(new java.awt.Color(255, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Food Name", "Qty", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btexrarea.setBackground(new java.awt.Color(255, 204, 204));
        btexrarea.setColumns(20);
        btexrarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btexrarea.setRows(5);
        jScrollPane2.setViewportView(btexrarea);

        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        evalatuionbuttom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        evalatuionbuttom.setText("Evalatuion Foods");
        evalatuionbuttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evalatuionbuttomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(evalatuionbuttom)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(evalatuionbuttom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 0, 760, 450));

        jPanel3.setBackground(new java.awt.Color(153, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, 81, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cash:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, 81, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Balance:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, 81, -1));

        totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalLabel.setText("00");
        jPanel3.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 24, 111, -1));

        balance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("00");
        jPanel3.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 125, 111, -1));
        jPanel3.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 85, 111, -1));

        payButton.setBackground(new java.awt.Color(255, 204, 102));
        payButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        payButton.setText("PAY");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        jPanel3.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 110, 94));

        printButton.setBackground(new java.awt.Color(255, 204, 102));
        printButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        printButton.setText("PRINT");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel3.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 110, 94));

        deletemyaccountbutton.setText("Delete My Account");
        deletemyaccountbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletemyaccountbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(deletemyaccountbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 452, 760, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cappuccinobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinobuttonActionPerformed

        int i = Integer.valueOf(countLabel4.getText());
        i++;
        countLabel4.setText(String.valueOf(i));
        String productName = "Cappuccino";
        seleceteditemNames.add(productName);
        addtable(4, productName, i, 79.90);
        cal();

    }//GEN-LAST:event_cappuccinobuttonActionPerformed

    private void chickenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenbuttonActionPerformed

        int i = Integer.valueOf(countLabel1.getText());
        i++;
        countLabel1.setText(String.valueOf(i));
        String productName = "Chicken Burger";
        seleceteditemNames.add(productName);
        addtable(1, productName, i, 159.90);
        cal();


    }//GEN-LAST:event_chickenbuttonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:

        double tot = Double.valueOf(totalLabel.getText());
        double paid = Double.valueOf(pay.getText());
        double bal = paid - tot;

        DecimalFormat df = new DecimalFormat("00.00");

        balance.setText(String.valueOf(df.format(bal)));

    }//GEN-LAST:event_payButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

        //check if the cash field is not empty
        if (pay.getText().isEmpty()) {

            JOptionPane.showMessageDialog(printButton, "Please enter the cash amount before printing.", "error", JOptionPane.ERROR_MESSAGE);
            return; // stop execution if cash is empty
        }

        try {
            btexrarea.setText("               FSMVU ONLINE CANTEEN SALES   \n\n");
            btexrarea.setText(btexrarea.getText() + " Fatıh Sultan Mehmet Unıversıty\n");
            btexrarea.setText(btexrarea.getText() + " Halıcıoğlu\n");
            btexrarea.setText(btexrarea.getText() + " Beyoglu/Istanbul\n");
            btexrarea.setText(btexrarea.getText() + "-------------------------------------------------------------------------\n");
            btexrarea.setText(btexrarea.getText() + "  Item \t\tQty \tPrice" + "\n");
            btexrarea.setText(btexrarea.getText() + "--------------------------------------------------------------------------\n");

            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();

            //get table product detailss babee
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                String Name = df.getValueAt(i, 1).toString();
                String Qty = df.getValueAt(i, 2).toString();
                String Price = df.getValueAt(i, 3).toString();

                btexrarea.setText(btexrarea.getText() + "" + Name + "\t\t" + Qty + "\t" + Price + "\n");
            }

            btexrarea.setText(btexrarea.getText() + "-------------------------------------------------------------------------\n");
            btexrarea.setText(btexrarea.getText() + "Sub Total: " + totalLabel.getText() + "\n");
            btexrarea.setText(btexrarea.getText() + "Cash: " + pay.getText() + "\n");
            btexrarea.setText(btexrarea.getText() + "Balance: " + balance.getText() + "\n");
            btexrarea.setText(btexrarea.getText() + "-------------------------------------------------------------------------\n");
            btexrarea.setText(btexrarea.getText() + "             Thanks For Your Business...." + "\n");
            btexrarea.setText(btexrarea.getText() + "-------------------------------------------------------------------------\n");
            btexrarea.setText(btexrarea.getText() + "            Bye..Come again, dont starve yourself :D " + "\n");

        } catch (Exception e) {
            System.out.println(e);
        }

        orderAndSaveToDatabase();


    }//GEN-LAST:event_printButtonActionPerformed

    private void orderAndSaveToDatabase() {
        try {

            Person loggedInUser = DatabaseManager.getloggedInUser();
            String username = loggedInUser.username;

            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myschema", "root", "123");

            String sql = "INSERT INTO orders (username,item_name) VALUES (?,?)";
            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

                for (String itemName : seleceteditemNames) {
                    preparedStatement.setString(1, username);
                    preparedStatement.setString(2, itemName);

                    // SQL sorgusunu çalıştır
                    preparedStatement.executeUpdate();
                }
            }
            connection.close();

            JOptionPane.showMessageDialog(this, " product purchased successfully...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " error occurred " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void chickennnoodlebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickennnoodlebuttonActionPerformed

        int i = Integer.valueOf(countLabel2.getText());
        i++;
        countLabel2.setText(String.valueOf(i));
        String productName = "Chicken Noodle";
        seleceteditemNames.add(productName);
        addtable(2, productName, i, 129.90);
        cal();


    }//GEN-LAST:event_chickennnoodlebuttonActionPerformed

    private void vegatarianpizzabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegatarianpizzabuttonActionPerformed

        int m = Integer.valueOf(countLabel3.getText());
        m++;
        countLabel3.setText(String.valueOf(m));
        String productName = "Vegatarian Pizza";
        seleceteditemNames.add(productName);
        addtable(3, productName, m, 149.90);
        cal();

    }//GEN-LAST:event_vegatarianpizzabuttonActionPerformed

    private void coldcofeebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldcofeebuttonActionPerformed
        // TODO add your handling code here:

        int i = Integer.valueOf(countLabel5.getText());
        i++;
        countLabel5.setText(String.valueOf(i));
        String productName = "Cold Coffe";
        seleceteditemNames.add(productName);
        addtable(5, productName, i, 79.90);
        cal();


    }//GEN-LAST:event_coldcofeebuttonActionPerformed

    private void orongejuicebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orongejuicebuttonActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(countLabel6.getText());
        i++;
        countLabel6.setText(String.valueOf(i));
        String productName = "Orange Juice";
        seleceteditemNames.add(productName);
        addtable(6, productName, i, 59.90);
        cal();
    }//GEN-LAST:event_orongejuicebuttonActionPerformed

    private void rainbowcakebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rainbowcakebuttonActionPerformed
        // TODO add your handling code here: 
        int i = Integer.valueOf(countLabel7.getText());
        i++;
        countLabel7.setText(String.valueOf(i));
        String productName = "Rainbow Cake";
        seleceteditemNames.add(productName);
        addtable(7, productName, i, 89.90);
        cal();
    }//GEN-LAST:event_rainbowcakebuttonActionPerformed

    private void chocalatecakebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocalatecakebuttonActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(countLabel8.getText());
        i++;
        countLabel8.setText(String.valueOf(i));
        String productName = "Chocolate Cake";
        seleceteditemNames.add(productName);
        addtable(8, productName, i, 79.90);
        cal();
    }//GEN-LAST:event_chocalatecakebuttonActionPerformed

    private void fruitcakebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitcakebuttonActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(countLabel9.getText());
        i++;
        countLabel9.setText(String.valueOf(i));
        String productName = "Fruit Cake";
        seleceteditemNames.add(productName);
        addtable(9, productName, i, 89.90);
        cal();

    }//GEN-LAST:event_fruitcakebuttonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        int selectedColumn = 1;

        if (selectedRow >= 0 && selectedRow < dt.getRowCount()) {
            Object selectedValue = dt.getValueAt(selectedRow, selectedColumn);

            if (selectedValue != null) {
                String selectedName = selectedValue.toString();

                String eslesenIsim = null;
                Iterator<String> iterator = seleceteditemNames.iterator();
                while (iterator.hasNext()) {
                    String foodName = iterator.next();

                    if (foodName.equals(selectedName)) {
                        iterator.remove();
                        eslesenIsim = foodName;
                    }
                }

                if (selectedRow != -1 && dt.getColumnCount() > 0) {
                    int priceColumnIndex = -1;

                    for (int i = 0; i < dt.getColumnCount(); i++) {
                        if (dt.getColumnName(i).equalsIgnoreCase("Price")) {
                            priceColumnIndex = i;
                            break;
                        }
                    }

                    if (priceColumnIndex != -1) {
                        double deletedItemPrice = Double.parseDouble(dt.getValueAt(selectedRow, priceColumnIndex).toString());

                        dt.removeRow(selectedRow);

                        double currentTotal = Double.parseDouble(totalLabel.getText());
                        double newTotal = currentTotal - deletedItemPrice;
                        DecimalFormat df = new DecimalFormat("0.00");
                        totalLabel.setText(df.format(newTotal));
                    } else {
                        System.out.println("Price column not found.");
                    }

                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void evalatuionbuttomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evalatuionbuttomActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        FoodsEvaluate evaluate = new FoodsEvaluate();
        evaluate.setVisible(true);
    }//GEN-LAST:event_evalatuionbuttomActionPerformed

    private void deletemyaccountbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletemyaccountbuttonActionPerformed

        setVisible(false);
        DeleteUser deleteuser = new DeleteUser();

        deleteuser.setVisible(true);
    }//GEN-LAST:event_deletemyaccountbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductManagment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JTextArea btexrarea;
    private javax.swing.JButton cappuccinobutton;
    private javax.swing.JButton chickenbutton;
    private javax.swing.JButton chickennnoodlebutton;
    private javax.swing.JButton chocalatecakebutton;
    private javax.swing.JButton coldcofeebutton;
    private javax.swing.JLabel countLabel1;
    private javax.swing.JLabel countLabel2;
    private javax.swing.JLabel countLabel3;
    private javax.swing.JLabel countLabel4;
    private javax.swing.JLabel countLabel5;
    private javax.swing.JLabel countLabel6;
    private javax.swing.JLabel countLabel7;
    private javax.swing.JLabel countLabel8;
    private javax.swing.JLabel countLabel9;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deletemyaccountbutton;
    private javax.swing.JButton evalatuionbuttom;
    private javax.swing.JButton fruitcakebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton orongejuicebutton;
    private javax.swing.JTextField pay;
    private javax.swing.JButton payButton;
    private javax.swing.JButton printButton;
    private javax.swing.JButton rainbowcakebutton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton vegatarianpizzabutton;
    // End of variables declaration//GEN-END:variables
}
